export enum RoutesNames {
  LOGIN = 'Login',
  BOTTOMTABS = 'BottomTabs',
  DASHBOARD = 'Dashboard',
  DASHDETAIL = 'DashDetail',
  WILDFOCUSDETAILS = 'WildFocusDetails',
  SERVEDCUSTOMERS = 'ServedCustomers',
  STATEMENT = 'Statement',
  INCENTIVES = 'Incentives',
  INCENTIVES_LIST = 'IncentivesList',
  INCENTIVECONSULT = 'IncentiveConsult',
  INCENTIVEDETAILSTABS = 'IncentiveDetailsTabs',
  INCENTIVESMARTINS = 'IncentivesMartins',
  INCENTIVESMARTINSTABS = 'IncentivesMartinsTabs',
  BEM = 'BEM',
  SAC = 'SAC',
  SACWEBVIEW = 'SACWEBVIEW',
  TUTORIALDETAIL = 'TutorialDetail',
  CUSTOMERSLIST = 'Clientes',
  PRIVACYPOLICY = 'PrivacyPolicy',
  NOTIFICATIONS = 'Notifications',
  NOTIFICATION_DETAILS = 'NotificationDetails',
  ORDERS = 'Orders',
  TEAMLIST = 'TeamList',
  RCAPROFILE = 'RCAProfile',
}
