# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger: none


resources:
  repositories:
    - repository: templates
      type: git
      name: 'Martins.DevSecOps/ci-cd-templates'
      ref: refs/tags/1.15-stable

parameters:
  - name: stage
    displayName: Build for homolog(alpha), Beta (staging) or Production?
    type: string
    default: homolog
    values:
    - homolog
    - production

variables:
- group: b2b-vendas

stages:
  - template: pipelines/ReactNative/build-pipeline.yaml@templates
    parameters:
      sonarQubeConnection: 'SonarQube Oficial-B2BVendas'
      bundleIdAndroid: 'com.martins_forcadevendas'
      stage: ${{ parameters.stage }}
      arquivoKeyStore: 'production.keystore'
      arquivoGradleProperties: 'gradle.properties.production'
      substituirKeystore: true
      googlePlayServiceConnection: 'google-play'
      buildIos: true
      bundleIdIos: 'com.gestaoforcadevendas'
      iosProjectName: 'martins_forcadevendas'
      iosDistributionCertificate: 'ios_production_distribution_v2.p12'
      iosCertificatePassword: $(ios_certificate_distribution_password)
      iosMobileProvisionFile: 'gestaoforcavendasdistribution.mobileprovision'
      iosBuildConfiguration: 'Release'
      iosTeamId: 'ZWY45T9CG7'
      environment: app-b2bvendas-forcavendas-${{ parameters.stage }}
      appleStoreServiceConnection: 'apple-store'
      evaluateQualityGate: false
      skipSnyk: 'true'
