export const customers = [
  {
    id: '1',
    newCustomer: false,
    creditStatus: 'Reabilitado',
    tradeName: 'Marcelo',
    companyName: 'Martins',
    cnpj: '1235',
    latitude: '1',
    visitingAddress: '2',
    distance: '200',
  },
  {
    id: '2',
    newCustomer: false,
    creditStatus: 'Suspenso',
    tradeName: 'Maria Smith',
    companyName: 'Carone',
    cnpj: '12398',
    latitude: '100',
    visitingAddress: 'Alameda dos anjos',
    distance: '500',
  },
  {
    id: '3',
    newCustomer: true,
    creditStatus: 'Normal',
    tradeName: 'Bruna',
    companyName: 'Extrabom',
    cnpj: '0976576',
    latitude: '8',
    visitingAddress: 'Alameda dos nada',
    distance: '200',
  },
  {
    id: '4',
    newCustomer: false,
    creditStatus: 'Cortado',
    tradeName: 'Monica',
    companyName: 'Supermercado',
    cnpj: '0000044',
    latitude: '10',
    visitingAddress: 'Hipermercado',
    distance: '900',
  },
];
